FROM node:18

WORKDIR /app

# Install dependencies
COPY mimosa-front/package.json mimosa-front/package-lock.json ./
RUN rm -rf node_modules && npm install

# Copy application code
COPY mimosa-front/ .

# Expose port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
