"""Tests for launcher failure classification from exit code + log tail."""

from __future__ import annotations

import pytest

from app.launcher import derive_failure


def test_healthy_run_yields_no_hint():
    assert derive_failure(None, "iteration 1 running fine\n") == (None, None)
    assert derive_failure(0, "done\n[bridge] run complete\n") == (None, None)


@pytest.mark.parametrize(
    "line",
    [
        "✗ No code generated by LLM.",
        "ValueError: LLM did not return valid workflow code",
        "create_workflow_genotype_code: LLM workflow generation/extraction failed: boom",
        "🚨 Invalid workflow code 🚨",
        "ValueError: LLM generated invalid Python syntax: unexpected EOF",
        "ValueError: No workflow nodes found",
        "craft_workflow: Workflow structure validation failed: missing END",
        "UUID:x|Assembled workflow has invalid syntax: bad indent",
    ],
)
def test_generation_failures_detected_even_while_running(line):
    tail = f"some earlier output\n{line}\nretrying...\n"
    hint, matched = derive_failure(None, tail)
    assert hint == "workflow_generation"
    assert matched == line.strip()


def test_generation_detection_is_case_insensitive():
    hint, _ = derive_failure(1, "NO CODE GENERATED BY LLM.")
    assert hint == "workflow_generation"


def test_crash_prefers_bridge_error_line():
    tail = "starting\n[bridge] ERROR: RuntimeError: MCP unreachable\ntrailing noise\n"
    assert derive_failure(1, tail) == ("crash", "[bridge] ERROR: RuntimeError: MCP unreachable")


def test_crash_falls_back_to_last_nonempty_line():
    assert derive_failure(137, "line one\nkilled\n\n") == ("crash", "killed")


def test_crash_with_empty_log():
    assert derive_failure(1, "") == ("crash", None)
